# Generated by Django 4.2.29 on 2026-03-16 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ChannelName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=64)),
                ('OwnerUsername', models.CharField(max_length=32)),
                ('ProfilePicture', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('SteamId', models.IntegerField(unique=True)),
                ('Password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('Username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('ProfilePicURL', models.TextField(max_length=2000)),
                ('Bio', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Content', models.TextField(max_length=500)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HarmonyBack.user')),
                ('ChannelSent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HarmonyBack.channel')),
                ('ServerSent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HarmonyBack.server')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='ServerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HarmonyBack.server'),
        ),
    ]
