# Generated by Django 4.2.29 on 2026-03-18 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonyBack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
