# Generated by Django 4.2.29 on 2026-03-23 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonyBack', '0003_user_friends_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='server',
            name='icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(related_name='joined_servers', to=settings.AUTH_USER_MODEL),
        ),
    ]
