# Generated by Django 4.2.29 on 2026-03-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonyBack', '0004_remove_server_profile_picture_server_icon_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
