# Generated by Django 4.2.29 on 2026-03-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonyBack', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='steam_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
