# Generated by Django 6.0.3 on 2026-03-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarmonyBack', '0008_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='genre_vector',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
